package net.theblackchamber.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.theblackchamber.model.Issue;

/**
 * Class _Milestone was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Milestone extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ISSUES_PROPERTY = "issues";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToIssues(Issue obj) {
        addToManyTarget("issues", obj, true);
    }
    public void removeFromIssues(Issue obj) {
        removeToManyTarget("issues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Issue> getIssues() {
        return (List<Issue>)readProperty("issues");
    }


}
