package net.theblackchamber.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.theblackchamber.model.Issue;
import net.theblackchamber.model.Milestone;
import net.theblackchamber.model.User;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends CayenneDataObject {

    public static final String CREATION_DATE_PROPERTY = "creationDate";
    public static final String DISPLAY_NAME_PROPERTY = "displayName";
    public static final String NAME_PROPERTY = "name";
    public static final String ISSUES_PROPERTY = "issues";
    public static final String MILESTONES_PROPERTY = "milestones";
    public static final String TO_USER_PROPERTY = "toUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date getCreationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setDisplayName(String displayName) {
        writeProperty("displayName", displayName);
    }
    public String getDisplayName() {
        return (String)readProperty("displayName");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToIssues(Issue obj) {
        addToManyTarget("issues", obj, true);
    }
    public void removeFromIssues(Issue obj) {
        removeToManyTarget("issues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Issue> getIssues() {
        return (List<Issue>)readProperty("issues");
    }


    public void addToMilestones(Milestone obj) {
        addToManyTarget("milestones", obj, true);
    }
    public void removeFromMilestones(Milestone obj) {
        removeToManyTarget("milestones", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Milestone> getMilestones() {
        return (List<Milestone>)readProperty("milestones");
    }


    public void setToUser(User toUser) {
        setToOneTarget("toUser", toUser, true);
    }

    public User getToUser() {
        return (User)readProperty("toUser");
    }


}
